---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8"
  EE_BUILDER_IMAGE: "registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8"

dependencies:
  galaxy: requirements.yml
